### ISSUE TITLE
[importer] Permettre l'import de toutes les règles enfant

### ISSUE THREAD

**Issue by Clemog** [EmileRolley/publiopti#42]
Lors de l'import de règles depuis un autre package, ce serait intéressant d'automatiser l'import de toutes les règles enfant d'un espace nom donné

**Comment by Clemog** [comment]
Exemple :

Eviter de genre d'imports auxquels vont s'ajouter ceux pour l'eau

```yaml
importer!:
  depuis:
    nom: '@incubateur-ademe/publicodes-negaoctet'
    url: https://github.com/incubateur-ademe/publicodes-negaoctet
  dans: negaoctet
  les règles:
    - acv . smartphone . carbone . fabrication
    - acv . smartphone . carbone . distribution
    - acv . smartphone . durée de vie théorique
    - acv . tablette . carbone . fabrication
    - acv . tablette . carbone . distribution
    - acv . tablette . durée de vie théorique
    - acv . ordinateur portable . carbone . fabrication
    - acv . ordinateur portable . carbone . distribution
    - acv . ordinateur portable . durée de vie théorique
    - acv . TV . carbone . fabrication
    - acv . TV . carbone . distribution
    - acv . TV . durée de vie théorique
    - acv . ordinateur fixe . carbone . fabrication
    - acv . ordinateur fixe . carbone . distribution
    - acv . ordinateur fixe . durée de vie théorique
    - acv . écran . carbone . fabrication
    - acv . écran . carbone . distribution
    - acv . écran . durée de vie théorique
    - acv . enceinte . carbone . fabrication
    - acv . enceinte . carbone . distribution
    - acv . enceinte . durée de vie théorique
    - acv . console de salon . carbone . fabrication
    - acv . console de salon . carbone . distribution
    - acv . console de salon . durée de vie théorique
    - acv . console portable . carbone . fabrication
    - acv . console portable . carbone . distribution
    - acv . console portable . durée de vie théorique
    - acv . imprimante . carbone . fabrication
    - acv . imprimante . carbone . distribution
    - acv . imprimante . durée de vie théorique
```
