### ISSUE TITLE
Bug: duplicated rules when importing `bilan` from NGC model 

### ISSUE THREAD

**Issue by EmileRolley** [EmileRolley/publiopti#45]
Original message :

Bonjour !

Je suis développeuse à l'ABC depuis peu, et je viens de découvrir ces discussions publicodes que je suis ravie de rejoindre !

J'ai une petite question, nous essayons d'importer les règles publicodes de nosgestesclimat dans un projet. J'aimerais importer toutes les règles, en en modifiant certaines et en en ajoutant. Pour l'instant je n'ai pas apporté de modifications car j'ai une erreur quand je compile juste en important la règle bilan (qui a beaucoup de dépendances), car il m'indique qu'une règle est définie deux fois. J'ai testé de compiler les règles NGC directement et cela fonctionne bien, je pense que le problème vient donc bien de l'import.

L'import que j'essaye de faire

```yaml
importer!:
  depuis:
    nom: '@incubateur-ademe/nosgestesclimat'
    url: https://github.com/incubateur-ademe/nosgestesclimat
  dans: ngc
  les règles:
    - bilan
```

L'erreur que j'ai

```
❌ An error occured while trying to parse the base rules:

   [ Erreur d'évaluation ]
   ➡️  Dans la règle "ngc . logement . vacances . résidence secondaire . localisation . littoral méditerranéen . facteur saison . facteur hiver"
   ✖️  La référence 'ngc . logement . vacances . résidence secondaire . localisation . littoral méditerranéen . facteur saison . facteur hiver' a déjà été définie
```

Est-ce que vous sauriez d'où pourrait venir cette erreur ? Est-ce dans ma façon d'importer ?
Est-ce que cet import est la bonne manière de faire ?

Merci d'avance pour vos réponses !
